name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/jekyll:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site
      run: jekyll build --future
