name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/jekyll:latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      run: |
        gem install bundler
        bundle install

    - name: Fix permissions
      run: |
        sudo chown -R $(whoami) /__w/pidctest/pidctest

    - name: Build the site
      run: jekyll build --future
