name: Jekyll site CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.1.1'

    - name: Set write permissions for Gemfile.lock
      run: |
        sudo chmod 777 /__w/pidctest/pidctest/Gemfile.lock

    - name: Install dependencies
      run: |
        bundle install

    - name: Build the site
      run: |
        bundle exec jekyll build